### ISSUE TITLE
Nunit support

### ISSUE THREAD

**Issue by alastairtree** [Microsoft/UnitTestBoilerplateGenerator#1]
Hi

Great extension, really useful. What would be involved in adding support for nunit? I often use the "Create unit tests" feature in Studio with the nunit adapter installed but the handling of Moq and DI in this extension is better so would happily swap if nunit was supported. I suspect this would increase potential userbase for this extension considerably.

Thanks

**Comment by RandomEngy** [comment]
Thanks! Added NUnit support in 1.4.1. It should automatically detect which projects are using it. Feel free to leave a review if this helps you out: https://visualstudiogallery.msdn.microsoft.com/f3f3b2a7-cefe-4ffe-add1-9740ae117252

**Comment by alastairtree** [comment]
Awesome, thanks!
