### ISSUE TITLE
DateTime object in Class Constructor Argument List Generated and Invalid Test Format

### ISSUE THREAD

**Issue by JimKay1941** [Microsoft/UnitTestBoilerplateGenerator#10]
### Installed product versions
- Visual Studio: [example 2017 Community]
- This extension: [example 1.5.2]

### Description
I have a class, Student with a constructor having a DateTime object in the argument list.

The extension created these statements:
private Mock<DateTime> mockDateTime;
mockDateTime = mockRepository.Create<DateTime>();

### Steps to recreate
1. Create a simple Class with DateTime as an object in the argument list.
2. Create a test for the Class
3. The above error(s) will appear. 
"the type 'DateTime' must be a reference type in order to use it as a parameter 'T' in the generic type or method 'mockfactory.create<T>()'"
"the type "System.DateTime" must be a reference type in order to use it as parameter 'T'"
### Current behavior
The generated statements cannot be copiled.

### Expected behavior
Put DateTime directly in the argument list and do not attempt to use moq.

**Comment by JimKay1941** [comment]
OOPS!
The erroneous generated lines are:
 private Mock<DateTime> mockDateTime;
this.mockDateTime = this.mockRepository.Create<DateTime>();

**Comment by JimKay1941** [comment]
It seem your system is editing out &gt; and &lt; so I will have to resubmit them.
private Mock&lt;DateTime&gt; mockDateTime;
this.mockDateTime = this.mockRepository.Create&lt;DateTime&gt;();

**Comment by RandomEngy** [comment]
Thanks for the report. Some types are not mockable, in this case DateTime. You'll need to create and inject it yourself. If I made a change here it would be to detect that DateTime is a non-mockable struct and insert "TODO" instead.

**Comment by JimKay1941** [comment]
Indeed, I have already done the inject myself.

I was only suggesting you make the change to detect DateTime as non-mockable. 

Thanks again for the reply and for your extension! It really helps me.

**Comment by RandomEngy** [comment]
Fixed in 1.5.10. We no longer try to make mock objects out of non-reference types.

**Comment by JimKay1941** [comment]
¡Muchas Gracias!
