### ISSUE TITLE
Feature request - Create stubs for methods

### ISSUE THREAD

**Issue by hanvyj** [Microsoft/UnitTestBoilerplateGenerator#11]
I'd love to see the boilerplate create a test stub for each public method (and property?) in the class with a simple Assert.Fail() rather than the current "TestMethod1"

**Comment by generik0** [comment]
Have you tryied NBuilder. It does this well... At least to make the stub?

**Comment by RandomEngy** [comment]
Implemented by PR from rCartoux, released in 1.9.
