### ISSUE TITLE
Feature Request: Support Rhino Mocks

### ISSUE THREAD

**Issue by phoenix-iv** [Microsoft/UnitTestBoilerplateGenerator#13]
I'd like to add support for Rhino Mocks.  I would be willing to implement it.

**Comment by RandomEngy** [comment]
Sounds great to me. A few places of interest:

MockFramework.cs: Where to add the new mock framework enum value
FindMockFramework in Utilities.cs: detecting what mock framework a project has
MockFrameworkAbstraction.cs: Controls which using statements are inserted into the file to reference the mock framework.
You'll want to make another subdirectory under DefaultTemplates and name it the same as the enum value, the files in it should be set as Embedded Resource

**Comment by RandomEngy** [comment]
I added support for it in 1.6.2.
