### ISSUE TITLE
How to generate NUnit test code?

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/UnitTestBoilerplateGenerator#14]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.5.2

### Description
I was created a NUnit 3 Unit Test project.  When I use **Unit Test Boilerplate Generator** to generate a new test class.  It used "Visual Studio Test" by default and I don't know where to configure this extension to use NUnit framework.  Is there any document on this? 

### Steps to recreate
1. Right click on an C# class file (project item) in the Solution Explorer.
2. Click "Create Unit Test Boilerplate"

### Current behavior
The code always generate "Visual Studio Test" framework code base.  

### Expected behavior
I was expected to use "NUnit" framework that my project current used.

**Comment by RandomEngy** [comment]
Thanks for the report. I've got a fix in the pipe for this that will be in the next release

**Comment by doggy8088** [comment]
Can I add new "Mock framework" template into options? 

![image](https://cloud.githubusercontent.com/assets/88981/25369454/897efae8-29b6-11e7-9b08-dd1f2ece40fa.png)

**Comment by RandomEngy** [comment]
No, NUnit is a test framework, not a mock framework. I'll have this bug fixed in the next release, hopefully. Just sit tight.

**Comment by doggy8088** [comment]
I know NUnit is not mock framework.  I mean I want to add more mock framework into this.  Is that possible to customize these templates by adding new mock framework into your extension?

**Comment by RandomEngy** [comment]
You can submit a pull request with your mock framework supported. I gave some advice on it here: https://github.com/Microsoft/UnitTestBoilerplateGenerator/issues/13

**Comment by doggy8088** [comment]
Thanks 👍

**Comment by RandomEngy** [comment]
Should be fixed in 1.5.10.

**Comment by ianrandell** [comment]
I've just downloaded v1.5.10 and I cannot get it to generate nunit boilerplate.
I'm using VS 2017, the project is a csproj-based .NetCoreApp 1.1 with NUnit v3.7.1 and NUnit3TestAdapter v3.8.0-alpha1 nugets.
Any ideas?

**Comment by testJunkie** [comment]
Same here, for .NetCoreApp 2.0, NUnit 3.7.1, Generator 1.5.10, Visual Studio 2017 15.3

**Comment by RandomEngy** [comment]
In 1.5.12 I fixed an issue with the auto-detect code for .NET Core projects, and added a choice to override the test framework or mock framework when generating the class.
