### ISSUE TITLE
Exception HRESULT 0x80004001 (E_NOTIMPL)

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/UnitTestBoilerplateGenerator#15]
### Installed product versions
- Visual Studio: 2017 Professional (15.2)
- This extension: 1.5.10

### Description

The generator was working fine for me, then suddenly (in the same session, without restarting VS), when right-clicking a file in the solution explorer and selecting "Create Unit Test Boilerplate", I got this error:

![error](https://cloud.githubusercontent.com/assets/7766733/26100469/45fb843e-3a2e-11e7-957d-b2fdfe9e31c9.png)

This now seems to happen for any file I try it with. I have tried uninstalling and reinstalling the plugin, as well as resetting the template to default settings. I have no idea what caused this in the first place, nor how to debug this to provide more information. Please let me know how I can assist.

**Comment by RandomEngy** [comment]
Hmm, that's not something I've seen before and it doesn't look like an error that my code generates. I think your best bet is to grab the source and see how far you get debugging. In the project properties under Debug, select "Start external program"

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe

Change this to your path to VS 2017.

The Command Line Arguments should be

    /rootsuffix Exp

It should start a sandboxed instance of Visual Studio and you can see how far it gets.

**Comment by RandomEngy** [comment]
Closing, I can't investigate further.
