### ISSUE TITLE
Allow lower-case field names for generated mocks

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/UnitTestBoilerplateGenerator#17]
According to standard naming rules, the mock field names should start with lowercase. For example, if a dependency has the name `IFoobar`, the test class field name for that dependency will currently be `Foobar`, while it should be `foobar`.

I therefore suggest you facilitate this somehow, e.g. by adding a token `$InterfaceMockNameLower$` or simply changing the casing rules for these fields.

**Comment by RandomEngy** [comment]
Changing any token to camelCase is possible since 1.6.4: https://github.com/Microsoft/UnitTestBoilerplateGenerator/wiki/Custom-Format-Tokens
