### ISSUE TITLE
Support csproj-based projects

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/UnitTestBoilerplateGenerator#18]
When the test project is csproj-based, the boilerplate generator does not seem to recognize the testing/mocking frameworks.

**Workaround:** Use the "Unknown" mock framework template. It's not perfect (the `using` statements are wrong), but gets you 90% of the way while waiting for a fix.

**Comment by RandomEngy** [comment]
I tested the behavior using csproj-based test projects. Can you share your test csproj? There may be a bug.

**Comment by cmeeren** [comment]
Sorry, I've moved on from this now. You may close it if you wish.

**Comment by RandomEngy** [comment]
I think your issue will be fixed in the upcoming release, but there are a few other issues tracking it.
