### ISSUE TITLE
Doesn't let me choose NSubstitute

### ISSUE THREAD

**Issue by grokky1** [Microsoft/UnitTestBoilerplateGenerator#19]
Latest VS2017 Community x64. Latest extension. Using .NET Core.

I go to tools and select NSubstitute.
I generate a test class
The test class is for Moq instead of NSubstitute.

**Comment by RandomEngy** [comment]
Sorry for taking so long to get a look at this. It looks like the auto-detect is failing. Can you share the .csproj file you're using?

**Comment by grokky1** [comment]
Was a while ago, but it was the standard csproj, basically from file->new project etc.

**Comment by RandomEngy** [comment]
In 1.5.12 I fixed an issue with the auto-detect code for .NET Core projects, and added a choice to override the test framework or mock framework when generating the class.
