### ISSUE TITLE
Support Windows Runtime and mock libs that work on it i.e. SimpleStubs

### ISSUE THREAD

**Issue by 4creators** [Microsoft/UnitTestBoilerplateGenerator#2]
## Description

Windows Runtime libraries (UWP) and components are not supported by majority of testing tools properly. It would be great to have it supported by this generator. Unfortunately the only mock library which supports WinRT is SimpleStubs library by Microsoft (if I am wrong pls correct me).

Jacek

**Comment by RandomEngy** [comment]
I added support for SimpleStubs in 1.4.1. Though if you want, you can still use Moq on UWP projects if the components you want to test are in PCL projects.
