### ISSUE TITLE
Cannot set the default template

### ISSUE THREAD

**Issue by lenssoliang** [Microsoft/UnitTestBoilerplateGenerator#21]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
In general, I need use the template of NSubstitude as the default. But it will always use the template of Moq. And I cannot change it on the options.

Could you consider add to support change the default template to use?

**Comment by RandomEngy** [comment]
It should automatically detect the NSubstitute reference in the project you're adding the test to and choose that template. Could you share your .csproj file so I can fix the auto-detect code? I may also add an "override" for people to force a certain mode or template...

**Comment by RandomEngy** [comment]
In 1.5.12 I fixed an issue with the auto-detect code for .NET Core projects, and added a choice to override the test framework or mock framework when generating the class.
