### ISSUE TITLE
Cannot add to existing test

### ISSUE THREAD

**Issue by generik0** [Microsoft/UnitTestBoilerplateGenerator#22]
### Installed product versions
- Visual Studio: 2017
- This extension: latest

### Description
i do not seam to be able to add to an existing test. I.e. a new test method. from the termplate.
Kan the extension not adding tests to existing unit test classes though automation?

### Steps to recreate
1. Have a test class created.
2. Then try to add/update to existing ctest class

### Expected behavior
I would like to be able to add a test on top of existing tests with new methods in a class

**Comment by RandomEngy** [comment]
What are you envisioning here? Why not just copy/paste an existing test case to make a new one? I think it would be easier to do that then navigate back to the original file to run the boilerplate generator again. All you would need to change is the name of the test.

**Comment by generik0** [comment]
You are right.
Except for when a interface of two where added to the class constructor :-/

**Comment by RandomEngy** [comment]
Yes, that scenario is different, and would be useful. It would be a bit harder given the use of custom templates to make the initial class. There would have to be a lot more logic to dig into the existing code and modify it. It's on the backlog though; just not for the initial release.

**Comment by generik0** [comment]
Fair enough
