### ISSUE TITLE
Default target framework and mock framework

### ISSUE THREAD

**Issue by generik0** [Microsoft/UnitTestBoilerplateGenerator#26]
Hi

Just want to start by saying that this extension is the best thing since sliced cheeeeszzee.

### Installed product versions
- Visual Studio: 2017
- This extension: newest

### Description
Is it possible that the tools->options can get a "IsDefault" for the test framework and the mock framework. So i don't need to change to NUnit and NSubstritute, which is my companies weapon of choice...

Regards, Rik

**Comment by RandomEngy** [comment]
The extension has logic to try and set those automatically by checking the .csproj for assembly and nuget references. Can you share the .csproj for the project you're using, so I can find out why the auto-detect logic isn't working for you?

**Comment by generik0** [comment]
@RandomEngy so that is why it sometimes finds the right stuff.

Our issue is that the test projects are old, and even though we use NUnit and NSub now, have used others in the past.
So unfortunately finds the wrong ones :-/

Strange thing is, we do not have VS test framework in tests but always finds that first.
I will see what I can find :-)

So this issues should be to assign a default, when more than one framework is present :-)

Br Rik

**Comment by RandomEngy** [comment]
It should be finding VS Test framework as a "last resort" if it doesn't find another framework. Would still be handy to see the .csproj file as there might be something more going wrong. Still, it's a good idea; I'll add a "preferred framework" feature to the backlog, to use when multiple frameworks or no frameworks are found.

**Comment by generik0** [comment]
Hi @RandomEngy  I found an example. The Test framework is incorrect, the mock framework is correct.

![image](https://user-images.githubusercontent.com/2411563/39291455-542811a2-4933-11e8-8a81-3427488546ab.png)

I have provided the csproj using email.

**Comment by RandomEngy** [comment]
Released 1.8.0, which does several things to help:

- Fixes an issue you were running into where framework references weren't getting detected if they were PackageReferences in a .csproj that uses the msbuild namespace.
- Adds an option to set the "preferred" mock and test framework that it will pick if it detects 0 or multiple frameworks.
- Adds display for the list of detected frameworks on the "create" dialog.

Remember to leave a review [on the marketplace](https://marketplace.visualstudio.com/items?itemName=RandomEngy.UnitTestBoilerplateGenerator) if you like the extension!
