### ISSUE TITLE
TODO - replace with a variable

### ISSUE THREAD

**Issue by Lechus** [Microsoft/UnitTestBoilerplateGenerator#27]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.8.0]

### Description
COnstructor - parameter "TODO" instead of integer

### Steps to recreate
Class with constructor with integer
Ctor(Interface service, int ala)

### Current behavior
putting "TODO" instead of a typed variable, like integer

### Expected behavior
variable of correct type

**Comment by RandomEngy** [comment]
That's by design. I wanted to make sure that it forced you to put something sensical in there, rather than throw in a default value that might be wrong.
