### ISSUE TITLE
Doesn't actually generate NUNit compatible unit tests

### ISSUE THREAD

**Issue by ravensorb** [Microsoft/UnitTestBoilerplateGenerator#3]
### Installed product versions
- Visual Studio: Visual Studio 2015 Enterprise w/Update 3
- This extension: 1.4.3
### Description

Creating a Unit test and placing in a NUnit based assembly generates a VS Test Tools Unit Test. 
### Steps to recreate

Create a Unit Test and select an assembly for output that contains NUnit tests
### Expected behavior

Ideally it would recognize that NUnit is being used in the destination assembly and create a unit test that leverages NUnit attributes and using clauses

**Comment by RandomEngy** [comment]
It should recognize that you have an NUnit assembly reference in your .csproj. It's searching for an NUnit.Framework assembly reference. Can you post your test assembly's .csproj file so I can figure out why it wasn't detected?

**Comment by ravensorb** [comment]
I wonder if it is because I am using a project.json file for packages -- in this case there is no references in the csproj file if I remember correctly.

**Comment by RandomEngy** [comment]
Yeah looks like that was the case. Should work in 1.4.5; now it checks the project.json for references as well.

**Comment by lennartb-** [comment]
![autotest](https://cloud.githubusercontent.com/assets/5563601/24186782/2c215752-0eda-11e7-8e7a-5862ecb28b1c.jpg)

Doesn't seem to detect NUnit 3 in VS 2017.

Reference in csproj is:

`  <Reference Include="nunit.framework, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>X:\NUnit\NUnit-3.4.1\bin\net-4.5\nunit.framework.dll</HintPath>
    </Reference>`

**Comment by RandomEngy** [comment]
@lennartb- The code is checking for nunit.framework references and that snippet looks exactly like what I've been testing against. Can you share the problematic .csproj so I can try and reproduce the issue?

Also what kind of project is it?

**Comment by lennartb-** [comment]
[Contoso.Fabrikam.csproj.txt](https://github.com/Microsoft/UnitTestBoilerplateGenerator/files/863861/Contoso.Fabrikam.csproj.txt)


Sure, here it is.
It's a C# Unit-Test project with .NET 4.6.1. I can try to put a minimal working example together if you can't repro it with the sample

**Comment by RandomEngy** [comment]
@lennartb- Should be fixed in 1.5.10, give it a try.

**Comment by lennartb-** [comment]
Works, thank you!
