### ISSUE TITLE
Extension v1.9.6 not working in VS 2015 Community

### ISSUE THREAD

**Issue by binpick** [Microsoft/UnitTestBoilerplateGenerator#31]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.9.6

### Description
Extension not working any more. Context menu does not show dialog. Options page cannot be displayed.

From the ActivityLog i get the error:

> LegacySitePackage failed for package [CreateUnitTestBoilerplateCommandPackage]Source: &apos;UnitTestBoilerplate&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.ComponentModelHost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies.

I figured out that the missing assembly is related to VS 2017 SDK. So seems that the extension for VS 2015 is referencing an assembly from VS 2017. In VS 2017 the extension is working properly.

**Comment by RandomEngy** [comment]
Should be fixed with 1.9.8.
