### ISSUE TITLE
Support for FluentValidation

### ISSUE THREAD

**Issue by btastic** [Microsoft/UnitTestBoilerplateGenerator#33]
### Description
I really like fluent validations as they give a more descriptive messages when things are going wrong.

### Current behavior
Currently the default `Assert` is used.

### Expected behavior
I can decide what asserting library I want to use - I saw a bunch of different asserting libraries, so might be a good start with FluentValidation

Link:
https://www.nuget.org/packages/fluentvalidation/

**Comment by RandomEngy** [comment]
We don't write a lot of Assert statements. Only the Assert.Fail in the stub tests I think.

One workaround would be to remove the $TestMethods$ part in the template and put in your own "starter" test with whatever assert statement you want. Though you'd only get the one test, and not one per public method.

A more general fix might be to add a template for the test method contents, so you could change what's put under the // Assert section. Would also probably need to add a list of namespaces to add in. With those two things you could set it up to whatever validation library you wanted.

**Comment by btastic** [comment]
Sounds cool! Thanks for the quick response!

**Comment by RandomEngy** [comment]
In 2.0 the test method code is generated from a customizable template.
