### ISSUE TITLE
Methods template

### ISSUE THREAD

**Issue by bartekpokerbartek** [Microsoft/UnitTestBoilerplateGenerator#37]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.9.10

### Description
Hello in Test Framework (NUnit) and Moq Framework (Moq) I have $TestMethods$ variable in template. Could You please advise how to change how generated functions are built? Can't find anything on how to do that.

For example I mean that function is generated like:
`[Test]
        public void GetNewCardData_StateUnderTest_ExpectedBehavior()
        {
            // Arrange
            var unitUnderTest = CreateService();

            // Act
            var result = unitUnderTest.GetNewCardData();

            // Assert
            Assert.Fail();
        }`

but I want it to look like ie.:
`[Test]
        public void GetNewCardData_StateUnderTest_ExpectedBehavior()
        {
            var result = _unitUnderTest.GetNewCardData();

            // Assert
            Assert.Fail();
        }`

Kind regards.

**Comment by rCartoux** [comment]
Hi,

You should be able to achieve that:

Go to Options > Unit Test Boilerplate Generator > Templates

Select and NUnit and Moq

Set 'Tested object creation format' to empty

Set 'Tested object reference format' to _unitUnderTest

**Comment by bartekpokerbartek** [comment]
Thanks,
for the info, it worked great.

Kind regards.
