### ISSUE TITLE
NullReferenceException when attempting to generate test class

### ISSUE THREAD

**Issue by johnmbaughman** [Microsoft/UnitTestBoilerplateGenerator#41]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.9.0
- This extension: 1.9.10

### Description
NullReferenceException when attempting to generate test class.
![image](https://user-images.githubusercontent.com/1634414/48588078-d77fb280-e8f2-11e8-9d1a-67def2378775.png)

Project implements Caliburn.Micro as the IoC framework. Test project uses Moq and xUnit.
Class has a single constructor with parameters; two are dynamic, others are instantiated objects and interfaces. Project is .NET Framework 4.6.2

### Steps to recreate
1. Select class to generate test class from
2. Ensure proper testing frameworks and project are selected. 
3. Click Create Unit Test Class button
4. Exception dialog should now be displayed.

### Current behavior
Exception dialog displays and no test class is generated.

### Expected behavior
No exception dialog displayed and test class is generated.

**Comment by RandomEngy** [comment]
Can you try with Visual Studio 2017 15.9.1? The extension was majorly broken in 15.9.0.

**Comment by johnmbaughman** [comment]
Awesome! That one worked! The other one didn't; I'll send you the project and packages.config files on that issue.
