### ISSUE TITLE
Unit Test Creation with SQL Server Database Project

### ISSUE THREAD

**Issue by a-t-k** [Microsoft/UnitTestBoilerplateGenerator#43]
### Installed product versions
- Visual Studio: [example 2017 Enterprise 15.9.9]
- This extension: [example 1.9.17]

### Description
I do have in my solution one project of type "sql server database project"
On create a new test with "Create Unit Test Boilerplate...." VS popup a error
"Could not find file 'c:\windows\system32\{$projectName}.sqlproj.

When i unload this mentioned project, create unit test boilerplate works

**Comment by RandomEngy** [comment]
Thanks for the report. This should be fixed in 1.9.20 . If you like the extension [rate it on the marketplace](https://marketplace.visualstudio.com/items?itemName=RandomEngy.UnitTestBoilerplateGenerator).
