### ISSUE TITLE
"Could not find class declaration" exception thrown when generating boiletplate

### ISSUE THREAD

**Issue by ghost** [Microsoft/UnitTestBoilerplateGenerator#44]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 1.9.20

### Description
Exception is thrown when creating unit test boilerplate.

### Current behavior
Creating a unit test boilerplate throws exception that says it could not find class declaration.

![image](https://user-images.githubusercontent.com/33554176/54980770-5080cc00-4faf-11e9-8a18-d6afa1851519.png)

### Expected behavior
It should create a unit test boilerplate.

#### Notes
It might help investigating that my project name starts with digits:
![image](https://user-images.githubusercontent.com/33554176/54981045-09dfa180-4fb0-11e9-98ee-6f2bf37eb71f.png)
But namespaces start with ordinary letters.

**Comment by RandomEngy** [comment]
Can you also post the contents of the file you were trying to make the test for?

**Comment by ghost** [comment]
Sorry, should've closed it earlier. As you can see in the last picture I attached, I have project names starting with number. The moment I've renamed the project to start with a letter instead, it worked.
