### ISSUE TITLE
Method not found 

### ISSUE THREAD

**Issue by LwServices** [Microsoft/UnitTestBoilerplateGenerator#46]
### Installed product versions
- Visual Studio: 2017
- This extension: 1.10.5

### Description
Crash after click button "Create Unit Test Class"

### Steps to recreate
1. Empty Soultion with two Projects
- Console Project
- MsTest Project

### Current behavior
Crash
![2019-07-11 07_00_15-Window](https://user-images.githubusercontent.com/667742/61023845-d46a9280-a3ab-11e9-8c72-1f897799413a.png)

**Comment by RandomEngy** [comment]
Thanks for the report. The "Immutable" library has given me some grief and it may be at it again. What specific version of VS 2017 are you using? (Help -> About Microsoft Visual Studio)

**Comment by LwServices** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Visual Basic 2017   00370-20004-22683-AA666
Microsoft Visual Basic 2017

Visual C# 2017   00370-20004-22683-AA666
Microsoft Visual C# 2017

Visual C++ 2017   00370-20004-22683-AA666
Microsoft Visual C++ 2017

Visual F# 4.1   00370-20004-22683-AA666
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2012   4.0.11203.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17114.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

CreateUnitTestBoilerplateCommand Extension   1.0
CreateUnitTestBoilerplateCommand Visual Studio Extension Detailed Info

Devart dotConnect for Oracle   9.5.520.0
Devart dotConnect for Oracle
Copyright 2002 - 2018 Devart. All rights reserved.
Web: www.devart.com/dotconnect/oracle
Support: support@devart.com

Devart Entity Developer   6.2.505.0
Devart Entity Developer
Copyright © 2008-2018 Devart. All rights reserved.
Web: www.devart.com/entitydeveloper 
Support: support@devart.com

Dotfuscator Community Edition   5.27.0.4679-release+ce-vs15.e4937ba.20161216.158
PreEmptive Protection - Dotfuscator CE

GitHub.VisualStudio   2.2.0.10
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2019.1.3   Build 191.0.20190704.212735
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.26309
Microsoft Office Developer Tools for Visual Studio 2017 ENU

Python   3.0.17114.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17114.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17114.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17114.1
Profiling support for Python projects.

Python - UWP support   3.0.17114.1
Provides templates and integration for the UWP framework.

R Tools for Visual Studio   1.1.30523.1233
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual C++ for Cross Platform Mobile Development (Android)   15.0.26228.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   15.0.26228.00
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development

Visual Studio Tools for Apache Cordova   15.113.6201.1
Visual Studio Tools for Apache Cordova

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by RandomEngy** [comment]
Hmm, 15.2 is a pretty old version. Can you try updating to the latest VS2017 - 15.9.14?

**Comment by LwServices** [comment]
I have downgraded Resharper to 2018.3 and it works fine.
At home i run vs 2017 15.9 and resharper 2019.1 works also.

It's look alike 15.2 and resharper 2019.1 creates this issues.

Thank you
