### ISSUE TITLE
Error at generating UnitTest MSTest "System.NullReferenceException"

### ISSUE THREAD

**Issue by jcmisena** [Microsoft/UnitTestBoilerplateGenerator#48]
### Installed product versions
- Visual Studio: enterprise 2019
- This extension: 2.0.0
### Description
http://prntscr.com/oqsuqx

### Steps to recreate
1. Right Click on Controller
2. Click on Generate Unite Test Boilerplate
3. Click on Create Unit Test Class
4. Opens a modal window with lines about the exception

**Comment by RandomEngy** [comment]
Can you post the code you were trying to create a test for?

**Comment by RealUlysse** [comment]
I have the same issue.
It comes from parameter attribute in my case. In the exemple below, it works if I remove FromBody attribute.
`public async Task<IHttpActionResult> MettreAJourPersonneRessource(int numeroPersonneRessource, [FromBody]PersonneRessource personneRessource)`

**Comment by RandomEngy** [comment]
Thanks for the reports and the bug details. This is fixed in 2.0.1.

Please [leave a review](https://marketplace.visualstudio.com/items?itemName=RandomEngy.UnitTestBoilerplateGenerator&ssr=false#review-details) if you like the extension!
