### ISSUE TITLE
Failing to generate unit test for structs

### ISSUE THREAD

**Issue by OJacot-Descombes** [Microsoft/UnitTestBoilerplateGenerator#49]
### Installed product versions
- Visual Studio: 2019 Community Version 16.5.0 Preview 2.0
- This extension: 2.2.0

### Description
Throws exception "InvalidOperationException: Could not find class declaration." when trying to generate unit test for a struct. I assume this is a current limitation. In this case consider this to be a feature request.

### Steps to recreate
1. Create as *.cs file containing only a struct.
2. Right click in solution explorer and select "Create Unit Test Boilerplate..."
3. Select Test Framework: VisualStudio
4. Select Mock Framework: NSubstitute
4. Click button "Create Unit Test Class"

### Current behavior
Throws exception "InvalidOperationException: Could not find class declaration." 

### Expected behavior
Should generate unit test.

**Comment by RandomEngy** [comment]
What kind of unit tests would you write for a struct?

**Comment by OJacot-Descombes** [comment]
Structs can have constructors and methods (in my specific case a Deconstructor). So, why not test them as I would for a class? Think of the `System.Drawing.Rectangle` struct. It has quite a complex implementation.

**Comment by RandomEngy** [comment]
So they do. I had always used classes when needing methods, etc. I'll look into it.

**Comment by RandomEngy** [comment]
Fixed in 2.3.0
