### ISSUE TITLE
Feature Request: Allow selection and generation of multiple classes at once

### ISSUE THREAD

**Issue by ravensorb** [Microsoft/UnitTestBoilerplateGenerator#5]
### Installed product versions
- Visual Studio: 2015 Enterprise w/Update 3
- This extension: 1.4.3
### Description

It would be great if I could select an entire project or multiple source files and generate tests for all of them at once.

**Comment by RandomEngy** [comment]
Have you tried multi-selecting source files, right-clicking and hitting "Generate"? It should work...

**Comment by ravensorb** [comment]
I tried that and it only generated a test for the 1st file in the selection.

**Comment by RandomEngy** [comment]
Hmm, I can't reproduce the problem. This is with ctrl clicking? Are they from the same folder?
