### ISSUE TITLE
Creating boilerplate unit testing project template

### ISSUE THREAD

**Issue by LeoJHarris** [Microsoft/UnitTestBoilerplateGenerator#53]
Hi there,

Ive used the generator to generate unit testing on a previous project but forgot how to use this to setup a blank unit testing project template? 

Am I imagining things or was this possible to create a blank unit testing project template because as I think I remember correctly I used this to setup a template project using NUnit and NSubstitute but cannot recall the steps. 

Im not referring to simply creating the boiler plate code for a class but rather an actual project template ready to begin adding unit test files. Can you confirm if this is possible otherwise I must have setup a project manually myself.

**Comment by RandomEngy** [comment]
This tool never set up entire projects. You can select multiple files and generate test files for all of them, however.

Setting up a unit test project is just a few clicks, fortunately.

**Comment by LeoJHarris** [comment]
@RandomEngy Okay I must have been mistaken, thanks 👍
