### ISSUE TITLE
Using "Import Project" in the test csproj (embedding the test framework in props) stops auto detection

### ISSUE THREAD

**Issue by generik0** [Microsoft/UnitTestBoilerplateGenerator#54]
### Installed product versions
- Visual Studio: VS 2019 V16.6.0
- This extension: 2.4.0

### Description
Looks like after VS16.6.0 update that the boilerplate:
- Using "Import Project" in the test csproj (embedding the test framework in props) stops auto-detection

![image](https://user-images.githubusercontent.com/2411563/82811911-2916df00-9e92-11ea-9092-bbb722442a6f.png)

### Steps to recreate
1. Create a central project props file
2. import the props file to the test csproj
3. Try to generate a test using boiler plate

![image](https://user-images.githubusercontent.com/2411563/82812066-6e3b1100-9e92-11ea-8b60-840bbb5f324c.png)

### Current behavior
It cannot "collect" the test and mock framework from the project import

### Expected behavior
The auto discover still works.

OR, is there an attribute or something we can add to the CSPROJ so it discovers the framework  + sub?

Thanks for WONDERFUL extension

**Comment by RandomEngy** [comment]
Just released 2.4.5, which should fix your issue. I added a step to check the references on the loaded project in the Visual Studio API, which catches references loaded by props files.

Give the extension [a nice review](https://marketplace.visualstudio.com/items?itemName=RandomEngy.UnitTestBoilerplateGenerator) if you like it!
