### ISSUE TITLE
Request of supporting JustMock

### ISSUE THREAD

**Issue by fengyuan213** [Microsoft/UnitTestBoilerplateGenerator#56]
### Installed product versions
- Visual Studio: 2019 Enterprise
- This extension: 1.1.21

### Description
Is it possible to support JustMock framework?

https://www.telerik.com/products/mocking.aspx
https://github.com/telerik/JustMockLite

**Comment by RandomEngy** [comment]
Added support for JustMock in 2.5.0. Make sure to rate the extension if you like it!
