### ISSUE TITLE
Getting error while generating test cases

### ISSUE THREAD

**Issue by neelesh02784** [Microsoft/UnitTestBoilerplateGenerator#57]
### Installed product versions
- Visual Studio: [example 2017 Professional]

### Current behavior
When I am creating test cases by right click on the file and click on"Create Unit Test For Boilerplate" the test file is generated but it is asking to add Visual studio or any of the desired test framework reference. Please find attachment herewith for your reference.

### Expected behavior
It should generate the test case without asking to add the reference of any of the framework
![BoilerPlate](https://user-images.githubusercontent.com/20293211/95984342-a989ac80-0e40-11eb-834c-3fc84cd49653.png)

**Comment by RandomEngy** [comment]
Generally you create a separate test project to contain your tests, and set it up with whatever test framework and mock framework you want to use. This tool will generate tests for you but it's not in the scope of the extension to set up test projects for you.
