### ISSUE TITLE
FR: Add NSubstitute mocking support

### ISSUE THREAD

**Issue by BlacKCaT27** [Microsoft/UnitTestBoilerplateGenerator#7]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
We're not using Moq so I end up removing a fair chunk of the generated code. I'm a huge fan of the template idea seen in Issue [6](https://github.com/Microsoft/UnitTestBoilerplateGenerator/issues/6), but aside from that, having native NSubstitute support as an option would be great. Perhaps in some kind of options/plugin configuration menu where you can specify how you want the template set up, which mocking framework to use, etc.

**Comment by RandomEngy** [comment]
Implemented in 1.5. Also added templating, so you can modify the test layout yourself.
